POST http://localhost:5000/api/salads HTTP/1.1
Content-Type: application/json

{
    "name": "Olivie",
    "weight": 2.0,
    "ingredients": ["potatoes", "chicken", "cucumber"],
    "sauce": "mayonesse",
    "dietType": "none",
    "isSpicy": false,
    "expired": "2023-09-29"
}